package server

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

const (
	APIBinPath        = "/usr/local/bin/atellar-api"
	APIEnvPath        = "/etc/atellar/api.env"
	SystemdUnitPath   = "/etc/systemd/system/atellar-api.service"
	DefaultMigrations = "/usr/share/atellar/migrations"
)

type InstallOptions struct {
	DatabaseURL         string
	MigrationsPath      string
	Port                string
	GRPCPort            string
	ClusterOverlayCIDR  string
	NodeSubnetPrefixLen int
	Start               bool
}

func ValidateInstallOptions(opts InstallOptions) error {
	if strings.TrimSpace(opts.DatabaseURL) == "" {
		return fmt.Errorf("--database-url is required")
	}
	if opts.Port == "" {
		return fmt.Errorf("--port is required")
	}
	if opts.GRPCPort == "" {
		return fmt.Errorf("--grpc-port is required")
	}
	if opts.MigrationsPath == "" {
		return fmt.Errorf("--migrations-path is required")
	}
	return nil
}

type InstallResult struct {
	EnvPath  string
	UnitPath string
}

func Install(opts InstallOptions) (*InstallResult, error) {
	if err := ValidateInstallOptions(opts); err != nil {
		return nil, err
	}

	if _, err := os.Stat(APIBinPath); err != nil {
		return nil, fmt.Errorf("atellar-api not found at %s (run release install.sh first)", APIBinPath)
	}
	if _, err := os.Stat(opts.MigrationsPath); err != nil {
		return nil, fmt.Errorf("migrations not found at %s", opts.MigrationsPath)
	}

	if err := os.MkdirAll("/etc/atellar", 0o755); err != nil {
		return nil, fmt.Errorf("create /etc/atellar: %w", err)
	}

	envContent := renderEnvFile(opts)
	if err := os.WriteFile(APIEnvPath, []byte(envContent), 0o600); err != nil {
		return nil, fmt.Errorf("write %s: %w", APIEnvPath, err)
	}

	if err := os.WriteFile(SystemdUnitPath, []byte(systemdUnit()), 0o644); err != nil {
		return nil, fmt.Errorf("write systemd unit: %w", err)
	}

	if err := runSystemctl("daemon-reload"); err != nil {
		return nil, err
	}
	if err := runSystemctl("enable", "atellar-api.service"); err != nil {
		return nil, err
	}
	if opts.Start {
		if err := runSystemctl("restart", "atellar-api.service"); err != nil {
			return nil, err
		}
	}

	return &InstallResult{EnvPath: APIEnvPath, UnitPath: SystemdUnitPath}, nil
}

func renderEnvFile(opts InstallOptions) string {
	lines := []string{
		"# Atellar control plane - generated by ateladm server install",
		fmt.Sprintf("DATABASE_URL=%s", opts.DatabaseURL),
		fmt.Sprintf("PORT=%s", opts.Port),
		fmt.Sprintf("GRPC_PORT=%s", opts.GRPCPort),
		fmt.Sprintf("MIGRATIONS_PATH=%s", opts.MigrationsPath),
		fmt.Sprintf("CLUSTER_OVERLAY_CIDR=%s", opts.ClusterOverlayCIDR),
		fmt.Sprintf("NODE_SUBNET_PREFIX_LEN=%d", opts.NodeSubnetPrefixLen),
		"",
	}
	return strings.Join(lines, "\n")
}

func systemdUnit() string {
	return fmt.Sprintf(`[Unit]
Description=Atellar Control Plane API
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=%s
ExecStart=%s
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
`, APIEnvPath, APIBinPath)
}

func runSystemctl(args ...string) error {
	cmd := exec.Command("systemctl", args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl %v failed: %s: %w", args, string(output), err)
	}
	return nil
}
